### PR TITLE
Adjustments to 1.23/1.24

### PR DESCRIPTION
**Pull request by Clonefusion**
added tradegoods incense, livestock, glass, gems, paper
adjusted trade good prices to this : https://forum.paradoxplaza.com/forum/index.php?threads/analysis-of-trade-good-tiers-and-prices.914875/#post-23767415
added some province event modifiers like diamond district, these probably have to be double checked to work, they probably dont work atm

### CODE REVIEW

**Comment by Idhrendur** [comment]
It looks like these changes are failing to build (some missing semicolons perhaps). That'll need to be fixed before we can merge it.

**Comment by kratostatic** [comment]
This looks great, thank you!  I'll be pulling this in once I've hotfixed the converter to deal with the current crashes as I need to be testing other things right at the minute but I'll get back to this!

**Comment by Clonefusion** [comment]
Kratostatic can u check if in current version with this change with change pop totals to yes from a 1444 save, falun converts with really high pop, probably best prov in europe, if it does, the prov modifier tool works and i shall add the missing ones like center of trade

**Comment by Clonefusion** [comment]
I dont know why a number change causes an issue

**Comment by Idhrendur** [comment]
So after fixing he merge issues, this is passing the checks. @kratostatic, do you think it's good to merge?

**Comment by kratostatic** [comment]
The reason I'm being slow about merging this in is that the current converter build doesn't actually convert saves so I can't easily test this to see how well it works.

**Comment by Clonefusion** [comment]
-Increasing detail in pop conversion via prov modifiers and territories
-Updating forts (forgot it at some point)
-Buffing tall nations (improving dev costs far more at high dev)
-Nerf buildings a bit (tax and prod changes in formula)
-Buffing/Adjusting development via setting it to same standard as buildings
-Add new trade goods
-Adjust trade good prices to be less late game dependent

To be done:
-Add other new trade goods
-Buff development a bit more possibly (balance between money and monarch points is hard to set right)
-Make territories potentially a bit less punishing (66% instead of 50%)
-Remove pop ratio effects from formula if pop conversion is used
-Make final culture conversion (final if several) have a base effect of 5% on all culture conversions (to make culture conversion not useless late game) if pop conversion is used (u should rly consider this in general)
-Remove continental effects on literacy if pop conversion is used

**Comment by Idhrendur** [comment]
With the new repo, this is now incompatible. It'll need to be redone against https://github.com/ParadoxGameConverters/EU4toVic2

**Pull request closed without merging**
