### PR TITLE
More HoI4 portraits

### PR DESCRIPTION
**Pull request by IohannesIohannium**
This is an enlargement of the number of portraits HoI4 has and that are used for the country leader generation of the converter.

Currently, it features two sources. The first (the one using the files of the "interface" subfolder) is from a mod, whose creator hasn't answered me yet. Therefore, I used an interface file to redirect to Vanilla HoI4 files until I get the okay to use his files (not in the upload here).

The second, instead, is the ones in the gfx/leaders/OC subfolder, which I created for the converter. You're all free to edit them and better them as you wish.

### CODE REVIEW

**Comment by Idhrendur** [comment]
I'm kind of inclined to wait until you hear back, just so we don't end up having to dig through and figure out which ones to remove if we don't get permission.

**Comment by IohannesIohannium** [comment]
No image from that mod has been added here, yet I listed the one that would be used in the interface file hashed out, giving default Vanilla redirect in the one that is uncommented (this latter to have the game work).

**Comment by Idhrendur** [comment]
I'm finally looking at PRs again.

Seeing as you never heard back from the other mod, can you completely remove any references to it and its portraits? I'll merge this in once you've done so.

**Comment by IohannesIohannium** [comment]
Could I just keep the names of the leaders? It'd remind me who to choose when/if I'll create the portraits ex novo.

**Pull request merged**
