### PR TITLE
1.25 and 1.26 Update

### PR DESCRIPTION
**Pull request by IohannesIohannium**
# UPDATE
- Added support for EU4 1.25 update (#503)
- Added support for EU4 1.26 update
- Added CK2 duchies: Latgale, Kaleva, Ostrobothnia, Savonia
- Added new Tokugawa flags (historical)
- Added new Syrian flags (historical)
- Added Dharma government mappings in the file "DharmagovernmentMapping.txt", explaining the works of it

# POST COLONIALISM
- Added colonial revolution events
- Added core-splitting Africa (player choice)
- Added post-Soviet split of Central Asia (if no independent country exists there)

# CULTURAL AND FORMABLE
- Removed Babylon and outside-German cultural core generation
- Added formable Turkestan as Central Asian union
- Made it possible for Nejd and Hejaz to form Arabia in case one of two doesn't exist
- Made Ha'il/Shammar able to form Arabia
- Added Occitania. The decision to form it removes French cores on the Occitan lands
- Added Occitan parties (for Auvergne, Avignon, and Provence)
- Added Gypsy and Aromanian cultures, generated as minorities
- Added Mormon minority conversions
- Added Cherokee cultural cores
- Added Picard and Assyrian cultural cores
- Fixed "Asian minor" Indian core hole
- Added Barbarian cultural group, along with needed nations
- Added the Roman Empire as formable (although by only a few nations)
- Fixed the Mashriqi cultural cores through event
- Added formable Indochina
- Added formable Caribbean and other Caribbean tags
- Integrated all NNM tags
- Added a couple more slave cultures and solved random noculture slaves appearing

# OTHER CODING
- Added Ottoman release of Egypt as event
- Fixed "Andhra" being used as conjunction
- Fixed cultural file question marks
- Added Turkish (and others) surnames as an option (manual edit required to activate)
- Fixed the Langobardia problem
- Fixed codings for Russian, Czech, Polish, and Hungarian localizations

### CODE REVIEW

**Comment by kratostatic** [comment]
Seen this, will be checking through properly through the week.

Also I should now be a bit better at noticing things on here, I've finally updated my email to the one I actually use regularly rather than the one that I should have lost access to years ago.

**Comment by Antafes** [comment]
Over a month has passed since the last comment on this pull request. Has anyone checked this and how long will it take till the next release of the EU4toVic2 converter?

**Comment by kratostatic** [comment]
Hey, @Antafes I'm the person who'll be checking this.  At the moment I'm part way (I hope over half-way) through a fairly major rewrite of the guts of the coding part of the converter.  Until that is done there's absolutely no point in messing about with data files.  For me it is good that this exists and I will pull it in (with any modifications as needed) once that bit of the project is done.

In terms of the next release, I don't really know, but probably not for a while yet (as in months not weeks).  Note that the current version (1.0Ha) does more or less work with EU4 1.25 with two and two halfs or so caveats.  The caveats being CK2 converted games are borked, Anglicanism isn't mapped, and the halfs being province mappings being outdated and an unknown occasional bug that I can't reproduce on my system at the moment.

**Comment by Antafes** [comment]
Hi @kratostatic,
I've already tested 1.0Ha and it doesn't work for me. I'm using a CK2 converted game playing as Saxony and as you've already mentioned, those are borked.

**Comment by IohannesIohannium** [comment]
Some may notice I added a post-colonial decision to liberate Africa (at the moment, just giving releasable cores). The result it would yeald (if all nations were liberated after taking it), would be this:
image

**Comment by IohannesIohannium** [comment]
I have added, as well, the possibility to split Central Asia in the fashion the Soviets did, always if post-colonialism enabled, if owning the whole region, and if having researched nationalism.

image

The decision comes with a forced migration into the new borders, simulating the Soviets IRL that made a mess at first.

**Comment by IohannesIohannium** [comment]
The islands of the Caribbean can now be released if the player wishes and they can strive to unite the Antilles (not shown: Jamaica and Bahamas).

image

**Comment by IohannesIohannium** [comment]
1.26 update in processing - files will be added and/or updated to support the Dharma patch, in the hope of a release soon after.

**Comment by IohannesIohannium** [comment]
Ignore the folder /EU4toV2/flags, I misuploaded it there. If you know how to delete it, thanks.

**Comment by IohannesIohannium** [comment]
Summary of this gargantuan pull request:

# UPDATE
- Added support for EU4 1.25 update
- Added support for EU4 1.26 update
- Added CK2 duchies: Latgale, Kaleva, Ostrobothnia, Savonia
- Added new Tokugawa flags (historical)
- Added new Syrian flags (historical)
- Added Dharma government mappings in the file "DharmagovernmentMapping.txt", explaining the works of it

# POST COLONIALISM
- Added colonial revolution events
- Added core-splitting Africa (player choice)
- Added post-Soviet split of Central Asia (if no independent country exists there)

# CULTURAL AND FORMABLE
- Removed Babylon and outside-German cultural core generation
- Added formable Turkestan as Central Asian union
- Made it possible for Nejd and Hejaz to form Arabia in case one of two doesn't exist
- Made Ha'il/Shammar able to form Arabia
- Added Occitania. The decision to form it removes French cores on the Occitan lands
- Added Occitan parties (for Auvergne, Avignon, and Provence)
- Added Gypsy and Aromanian cultures, generated as minorities
- Added Mormon minority conversions
- Added Cherokee cultural cores
- Added Picard and Assyrian cultural cores
- Fixed "Asian minor" Indian core hole
- Added Barbarian cultural group, along with needed nations
- Added the Roman Empire as formable (although by only a few nations)
- Fixed the Mashriqi cultural cores through event
- Added formable Indochina
- Added formable Caribbean and other Caribbean tags
- Integrated all NNM tags

# OTHER CODING
- Added Ottoman release of Egypt as event
- Fixed "Andhra" being used as conjunction
- Fixed cultural file question marks
- Added Turkish (and others) surnames as an option (manual edit required to activate)
- Fixed the Langobardia problem
- Fixed codings for Russian, Czech, Polish, and Hungarian localizations

**Comment by kratostatic** [comment]
Ok, presumably this is all saved on your branch?  It's gotten so big I literally can't see all the changes!  

Also we're going to do the same thing to EU4toV2 as Idhrendur did to V2toHOI4 so this request will be closed soon, and I can't pull with merge conflicts.

**Comment by Idhrendur** [comment]
With the new repo, this is now incompatible. It'll need to be redone against https://github.com/ParadoxGameConverters/EU4toVic2

**Pull request closed without merging**
